# Site settings
name: 愚公移山
email: 2456567972@qq.com
author: Xiang-Dong.Yuan
url: "https://yxdh4620.github.io"
resume_site: https://github.com/yxdh4620
github: https://github.com/yxdh4620/
baseurl: ""
description: Blog, Xiang-Dong.Yuan!
meta_description: 袁向东;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: ''
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yxdh4620

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

